### ISSUE TITLE
TaxonomyArchiveGenerator doesn't pass taxonomy siblings list

### ISSUE THREAD

**Issue by carbontwelve** [carbontwelve/tapestry#31]
Using a Taxonomy archive page with the following frontmatter:

```
---
title: Category Archive
use:
    - blog_categories
generator:
    - TaxonomyArchiveGenerator
    - PaginationGenerator
pagination:
    provider: blog_categories
    perPage: 3
---
```

You would expect to be able to see a list of taxonomy siblings passed through to the view being able to be displayed via `$blog_categories` with the current pages items being displayed via `$blog_categories_items`. This is a side effect of me attempting to keep the `use` system simple.

A workable fix should be by adding a Taxonomy view helper class that gets attached the view containing all the taxonomy siblings and the items requested for the current page.
