### ISSUE TITLE
PaginationGenerator does not generate correctly for blog index

### ISSUE THREAD

**Issue by carbontwelve** [carbontwelve/tapestry#50]
To reproduce create the file `source\blog\index.phtml` with the below font matter:

```
---
layout: default
title: Blog Archive
use:
    - blog
    - blog_categories
generator:
    - PaginationGenerator
pagination:
    provider: blog
    perPage: 3
---
```

Expected behaviour is that the files `blog\index.html`, `blog\1\index.html`, etc are generated. What actually happens is `blog\index.html` gets generated as expected and then `index\2.html`, `index\3.html` and so on plus the urls that the pagination pages use are all incorrectly set to `blog\index`.
